### ISSUE TITLE
Update v1 tag to point to latest v1.1.0 release

### ISSUE THREAD

**Issue by gonadarian** [iFaxity/wait-on-action#10]
Shorthand single-digit tags should be kept up to date, to always point to latest minor/patch release. In this case, [v1](https://github.com/iFaxity/wait-on-action/releases/tag/v1) should point to same commit as [v1.1.0](https://github.com/iFaxity/wait-on-action/releases/tag/v1.1.0) is.

**Comment by iFaxity** [comment]
Hi @gonadarian, sorry for the...almost 1 year wait.

The v1 tag now points to the v1.1.0 release.
Also a new release will be up soon to update some dependencies.
This will then be the new v1 tag.

**Comment by iFaxity** [comment]
The tag will be updated to v1.2.0 once it has been out for a while to test if there's not any major issues.
