### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by eserte** [iFaxity/wait-on-action#12]
In a GitHub workflow run which is using ifaxity/wait-on-action@v1.1.0:

>Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: ..., ifaxity/wait-on-action@v1.1.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by fede843** [comment]
waiting for this as well

**Comment by mlahargou** [comment]
https://github.com/iFaxity/wait-on-action/pull/16

**Comment by iFaxity** [comment]
This should now be updated with the release of v1.2.0
