### ISSUE TITLE
Unable to get action to start based on example

### ISSUE THREAD

**Issue by Asuza** [iFaxity/wait-on-action#2]
I spent a lot of time trying to figure out why this action wouldn't work, but in the end it was the fact that `uses: ifaxity/wait-on-action` is apparently case-sensitive. Ultimately, `uses: iFaxity/wait-on-action@v1` worked for me.

I got a lot of errors about either not being able to find the action or not being able to find the version until I made sure the casing of `iFaxity` was correct.

**Comment by itayganor** [comment]
Oh my god. I spent so much time on this. Thank you!

**Comment by mixn** [comment]
Thank you. :)

**Comment by cullylarson** [comment]
Was just coming here to post this exact issue.

**Comment by iFaxity** [comment]
Hi @Asuza, great catch, I will update the information in the README.
